version: '3'

services:
  spotify_api:
    build: api/
    ports:
      - 5001:5001
    volumes:
      - ./api/:/usr/src/app
    env_file:
      - .env
  discord_bot:
    build: chatbot/
    volumes:
      - ./chatbot/:/app/
    container_name: discord_bot
    env_file:
      - bot.env
    depends_on:
      - spotify_api
    links:
      - "spotify_api:api"